### ISSUE TITLE
discord link dead

### ISSUE THREAD

**Issue by tonyphoang** [SynoCommunity/synobot-discord#1]
is there a new discord invite link? the one on the synocommunity.com webpage is dead.

**Comment by mreid-tt** [comment]
It seems to be working, when I click it it goes to this URL: https://discord.com/invite/nnN9fgE7EF and then shows this page:

<img width="502" alt="Screenshot 2023-10-02 at 8 34 08 PM" src="https://github.com/SynoCommunity/synobot-discord/assets/943378/42e25aaf-63f9-49c9-93bd-0c108a3754bb">

Can you share what has been your experience?

**Comment by tonyphoang** [comment]
On the desktop, when I clicked on the link it would take me to my 'messages' panel. When I switched to my phone and clicked on the link, it was able to add the channel to discord.
